### ISSUE TITLE
Duvida

### ISSUE THREAD

**Issue by HugoLibanori** [trindadematheus/whastapp-sticker-bot#2]
bot top funcionando certinho, teria como mudar o tempo das figurinha? sei que e´1mb mas dependendo do gif da pra colocar ate 10 segundos. como faço isso? vlw

**Comment by trindadematheus** [comment]
Não sei se a biblioteca que eu usei permite mais de 5 segundos, eu deixei o que vem por padrão que é mostrado na documentação. Mas você pode passar um objeto como parâmetro na função `sendMp4AsSticker`  com umas configurações, e entre elas tem a `startTime` e a `endTime`.

Você pode não enviar o `startTime` para que ele utilize o default `00:00:00.0` e setar o `endTime` para `00:00:10.0`, assim vão ser 10 segundos de duração.

Aplicando na função `sendMp4asSticker` dentro do arquivo `CreateAnimatedStickerFromVideo.ts`

```javascript
await client.sendMp4AsSticker(
    from,
    `data:${mimetype};base64,${base64data}`,
    { endTime: '00:00:10.0' }
  )
```

**Comment by Spofff** [comment]
> Não sei se a biblioteca que eu usei permite mais de 5 segundos, eu deixei o que vem por padrão que é mostrado na documentação. Mas você pode passar um objeto como parâmetro na função `sendMp4AsSticker` com umas configurações, e entre elas tem a `startTime` e a `endTime`.
> 
> Você pode não enviar o `startTime` para que ele utilize o default `00:00:00.0` e setar o `endTime` para `00:00:10.0`, assim vão ser 10 segundos de duração.
> 
> Aplicando na função `sendMp4asSticker` dentro do arquivo `CreateAnimatedStickerFromVideo.ts`
> 
> ```js
> await client.sendMp4AsSticker(
>     from,
>     `data:${mimetype};base64,${base64data}`,
>     { endTime: '00:00:10.0' }
>   )
> ```

Matheus, te mandei um email sobre uma dúvida... se não for mt incômodo é claro.
Valeu!

**Comment by HugoLibanori** [comment]
Não mano tranquilo, eu testei aqui oq vc falou mas ele não cria o sticker,
aparece lá uma mensagem o CMD. Acho que deve ser algum bloqueio do
whatsapp, pois uns sticker que tenho aqui acima de 5 segundos não dá pra
enviar mais. Mas vlw pela atenção mano.

Eu msm não manjo muito de programação tô estudando python agora. 😁

Em sáb, 28 de nov de 2020 22:10, Spofff <notifications@github.com> escreveu:

**Comment by trindadematheus** [comment]
Boa, não sei seu nível de experiência em Python, mas tenta depois implementar um bot de stickers igual ao meu só que com Python, a organização que criou a biblioteca que eu utilizei pra Node, tem uma versão dela em Python.

Eu criei esse bot pra estudar um pouco mais de TypeScript, então acho que você se desafiar a criar um em Python deve ajudar em seus estudos também

https://github.com/open-wa/wa-automate-python
